[project]
name = "conco"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "django>=5.2.10",
    "django-cleanup>=9.0.0",
    "pillow>=12.1.0",
    "unidecode>=1.4.0",
]
